name: Deploy Frontend

on:
  push:
    branches:
      - main   # Change if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout (optional if you need workflow files)
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup SSH agent with private key from secrets
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy frontend to EC2
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            FRONTEND_DIR=/var/www/react

            if [ ! -d \$FRONTEND_DIR/.git ]; then
              echo 'Repo not found. Cloning...'
              sudo rm -rf \$FRONTEND_DIR
              sudo git clone git@github.com:premnathait1281-cloud/new-autodeploy1.git \$FRONTEND_DIR
            else
              echo 'Repo exists. Pulling latest changes...'
              cd \$FRONTEND_DIR
              sudo git config --global --add safe.directory \$FRONTEND_DIR
              sudo git reset --hard
              sudo git pull
            fi

            # Ensure correct permissions for Nginx
            sudo chown -R www-data:www-data \$FRONTEND_DIR
          "

      # Step 4: Restart Nginx
      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            sudo systemctl restart nginx
          "
